.TH MACPAC "1" "July 2023" "macpac 0.2" "Commands"
.SH NAME
macpac \- a tiny HTTPS-based package installer for macOS, written in (near)-POSIX shell.
.SH SYNOPSIS
.B macpac
[\fI\,COMMAND\/\fR] [\fI\,PACKAGE\/\fR]
.SH ENVIRONMENT VARIABLES
.TP
\fB\/MACPAC_INSTALL_PATH\fR
a directory exported to $PATH that macpac can install to.

\fB\/EXAMPLE:\fR export MACPAC_INSTALL_PATH="/usr/local"
.TP
\fB\/MACPAC_REPO\fR
an http(s) link to a list of package .tar.gz files

\fB\/EXAMPLE:\fR export MACPAC_REPO="https://repo.mysite.com/repo.html"
.SH COMMANDS
.TP
\fB\/--install\fR
search ${MACPAC_REPO} for a package and install it.
.TP
\fB\/--uninstall\fR
search ${MACPAC_REPO} for a package and uninstall it.
.TP
\fB\/--examine\fR
search ${MACPAC_REPO} for a package and search its contents.
.TP
\fB\/--bins \fR
display all installed binaries in ${MACPAC_INSTALL_PATH}
.TP
\fB\/--help \fR
show a quick help screen.
.TP
\fB\/--list \fR
originally oooa-app-env, enter an environment that automatically lets macpac use the right arguments for installing dmg packages.
.TP
\fB\/--selfup\fR
originally oooa-app-env, enter an environment that automatically lets macpac use the right arguments for installing dmg packages.
.TP
\fB\/--stats\fR
originally oooa-app-env, enter an environment that automatically lets macpac use the right arguments for installing dmg packages.

.SH AUTHOR
Written by draumaz.
